### ISSUE TITLE
Generate CSV report

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/open-source-library-data-collector#10]
#68

**Comment by andela-ijubril** [comment]
Hi @thinkingserious, I would like to take a shot at this.
Can you give me more info on what you have in mind here?

**Comment by thinkingserious** [comment]
Hello @andela-ijubril,

The generate_csv function should export the contents of the databases formatted as comma separated values to a .csv file.

**Comment by hydrosquall** [comment]
Hi @thinkingserious, I'd like to take this on for Hacktoberfest :).

**Comment by hydrosquall** [comment]
@thinkingserious , would you be interested in having the outputted CSV files be attached to the email that gets sent, or should they just be written to the local host file system?

I was thinking of letting someone put `has_attachment` followed by a path to a local file in the config file as a way to add this behavior. I could do this as part of this issue, or file a new one- let me know what would be best for you!

**Comment by hydrosquall** [comment]
@thinkingserious, I decided to just do the `export_file` function in PR #68, and save the email attachment idea for another issue if someone wants to take that up.
