### ISSUE TITLE
Implement Heroku button

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/open-source-library-data-collector#11]

**Comment by andela-ijubril** [comment]
Hi @thinkingserious I would like to take this. Thanks

**Comment by thinkingserious** [comment]
It's all yours :)

We will need a signed CLA to merge your work, could you please take care of that for us? https://github.com/sendgrid/open-source-library-data-collector/blob/master/CONTRIBUTING.md#cla

Thanks!
