### ISSUE TITLE
Error during setup due to wrong database name in .env

### ISSUE THREAD

**Issue by Deborah-Digges** [sendgrid/open-source-library-data-collector#142]
### Issue Summary

- The database name given in the .env file does not match that given in the create database instructions
- This results in the following error during setup:
```
  File "/Users/ddigges/github/open-source-library-data-collector/venv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1049, "Unknown database 'open-source-external-library-data'")
```

### Steps to Reproduce

1. Follow the setup instructions at the [Contributing guide](https://github.com/sendgrid/open-source-library-data-collector/blob/ed396ea2ac000dc0a521a572b3f6b7754901338f/CONTRIBUTING.md).
2. When you try to run the app using `python app.py`, the following error will appear:
```
  File "/Users/ddigges/github/open-source-library-data-collector/venv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1049, "Unknown database 'open-source-external-library-data'")
```
This is confusing for first time contributors.

### Technical details:

* Python Version:  3.6.3
* Browser/OS: Chrome/Mac
* Database/Version: Ver 8.0.12 for macos10.13 on x86_64 (MySQL Community Server - GPL)

**Comment by thinkingserious** [comment]
Fixed by #141
