### ISSUE TITLE
Remove illegal characters from example table name

### ISSUE THREAD

**Issue by hydrosquall** [sendgrid/open-source-library-data-collector#62]
While working on https://github.com/sendgrid/open-source-library-data-collector/issues/10 for hacktoberfest, I was unable to execute the create table command in the setup directions. It appears that `-` character is not allowed in a table name, as I got the following error message:

```bash
($): mysql -u root -p -e "CREATE DATABASE IF NOT EXISTS open-source-external-library-data"
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-source-external-library-data' at line 1
```

Replacing this character with an underscore fixes the problem. I will file a pull request fixing this example shortly.

### Local Environment

I am developing on a Mac Sierra 10.12.6, using the Homebrew version of mysql (`brew install mysql`).

**Comment by mbernier** [comment]
Nice, thank you!!
