### ISSUE TITLE
Add TROUBLESHOOTING.md

### ISSUE THREAD

**Issue by mbernier** [sendgrid/open-source-library-data-collector#89]
We need a TROUBLESHOOTING doc. 

This should include some good information about how to troubleshoot the data collector. 

We understand that you may not know all there is to know about this repo, that's ok!  Please take the TROUBLESHOOTING doc from [sendgrid-python](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md), and remove the following:
- Migrating from v2 to v3
- Continue using v2 
- Testing v3 /mail/send Calls Directly
- Viewing the Request Body
- Using the Package Manager

Then commit it and call it day, you win!

**Comment by thepriefy** [comment]
I have a question. Do I have to change the issue url from pointing to python repo to this repo? (I've already changed it to this repo but I can change it back if you want to.) @mbernier
