### ISSUE TITLE
Update the license file to have the correct date range

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/open-source-library-data-collector#97]
This license file might have the wrong end year (2017). If this is the case, please make a PR that updates the year. If the year is correct, please close this issue!

**Comment by xerosanyam** [comment]
The MIT license in this repo, mentions just the year '2016'. 
Shouldn't it be '2016, 2017' or just '2017' ?

**Comment by xerosanyam** [comment]
Researched. Both years should be included. ie.  '2016, 2017'
